services:
  app:
    image: chilitooo/drges-tracker-app:latest
    container_name: drges_app
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy   # ✅ waits until MySQL is truly ready
    restart: on-failure
    environment:
      ADMIN_EMAIL: admin@carsu.edu.ph
      ADMIN_NAME: Admin User
      ADMIN_PASSWORD: password

  db:
    image: mysql:8.0
    container_name: drges_db
    restart: always
    environment:
      MYSQL_DATABASE: drges_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drges_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s       # check every seconds
      timeout: 30s        # wait max seconds for response
      retries: 10        # try 10 times before giving up
      start_period: 30s  # give MySQL 30s to initialize first

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drges_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy   # ✅ phpmyadmin also waits for MySQL

volumes:
  db_data: